config/routes.rb
Rails.application.routes.draw do
	get ':controller(/:action)', controller: /[^\/]+/, action: /stats/

  resources :pedidos, except: [:edit, :update] do
		resources :pedidos_cantidades, except: [:index, :show]
	end

	get 'pedidos/:id/recibir', to: 'pedidos#recibir', as: 'recibir_pedido'
  get 'pedidos/:id/place', to: 'pedidos#place', as: 'place_pedido'

  resources :ordenes do
		resources :ordenes_cantidades, except: [:index, :show]
	end

  get 'ordenes/:id/place', to: 'ordenes#place', as: 'place_orden'
  get 'ordenes/:id/asignar_repartidor', to: 'ordenes#asignar_repartidor', as: 'asignar_repartidor'
	patch 'ordenes/:id/update_repartidor', to: 'ordenes#update_repartidor', as: 'update_repartidor'
  get 'ordenes/:id/entregar', to: 'ordenes#entregar', as: 'entregar_orden'

  resources :repartidores

  resources :clientes do
		resources :tiendas_clientes, shallow: true
  end

  resources :relojes

  resources :vendedores

  resources :proveedores

  devise_for :users, :skip => [:registrations]                                          
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
	end

	post 'ordenes/update_tiendas', as: 'update_tiendas'
	post 'ordenes_cantidades/update_relojes', as: 'update_relojes'
  get 'reparto', to: 'reparto#index', as: 'reparto'

  root 'home#inicio'

	get '*path' => redirect('/')

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	belongs_to :vendedor, inverse_of: :clientes
  has_many :tiendas_clientes, inverse_of: :cliente, dependent: :destroy

	validates :nombre, :telefono, :direccion_fiscal, :rfc, :vendedor_id, presence: true
  validates :nombre, :telefono, :rfc, uniqueness: true  
	validates :nombre, :direccion_fiscal, length: { maximum: 50 }
  validates :telefono, length: { in: 8..10 }, numericality: true
  validates :rfc, length: { is: 13 }

	default_scope { where(activo: true) }

	def self.to_csv
		CSV.generate do |csv|
		  csv << ['id', 'nombre', 'teléfono', 'dirección fiscal', 'RFC', 'responsable']
		  all.each do |cliente|
				csv << [cliente.id, cliente.nombre, cliente.telefono, cliente.direccion_fiscal, cliente.rfc, cliente.vendedor.nombre]
		  end
  	end
	end

	def self.count_by_vendedor(vendedor)
		self.where("vendedor_id = ?", vendedor.id).count
	end

	def self.con_tiendas
		Cliente.joins(:tiendas_clientes).distinct.order('nombre asc')
	end
	
	def tiendas_unscoped
		TiendaCliente.unscoped.where(cliente_id: id)
	end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :ensure_admin!, except: [:index, :show]
	before_action :ensure_vendedor!, only: [:index, :show]
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = current_user.vendedor ? current_user.vendedor.clientes : Cliente.all

		respond_to do |format|
      format.html { render layout: "dataTables" }
			format.csv { send_data @clientes.to_csv }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
		unless current_user.tiene_permiso_sobre? @cliente
			redirect_to clientes_url, alert: 'No tienes los permisos necesarios para ver ese cliente.'
		end
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'El cliente se creó exitosamente.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
			@cliente.attributes = cliente_params
			if @cliente.vendedor_id_changed?
				@cliente.fecha_asignacion = Time.now
			end
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'El cliente se actualizó exitosamente.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
		if Orden.por_cliente(@cliente).empty?
    	@cliente.destroy
      redirect_to clientes_url, notice: 'El cliente se borró exitosamente.'
    else
			@cliente.update(activo: false)
			@cliente.tiendas_clientes.update_all("activo = false")
			redirect_to clientes_url, notice: 'El cliente se ha desactivado.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :direccion_fiscal, :rfc, :vendedor_id)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h4>Hay <%= pluralize(@cliente.errors.count, "error") %>:</h4>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-lg-6">
		<div class="form-group">
		  <%= f.label :nombre %><br>
		  <%= f.text_field :nombre, class: "form-control" %>
		</div>
		<div class="form-group">
		  <label>RFC</label><br>
		  <%= f.text_field :rfc, class: "form-control" %>
		</div>
		<div class="form-group">
		  <%= f.label :teléfono %><br>
		  <%= f.text_field :telefono, class: "form-control" %>
		</div>
		<div class="form-group">
		  <%= f.label :dirección_fiscal %><br>
		  <%= f.text_field :direccion_fiscal, class: "form-control" %>
		</div>
		<div class="form-group">
      <label>Vendedor</label><br>
      <%= f.collection_select(:vendedor_id, Vendedor.all.order('nombre asc'), :id, :nombre, {prompt: "Selecciona"}, {class: "form-control"}) %>
    </div>
		<div class="actions">
		  <%= link_to 'Cancelar', clientes_path, class: "btn btn-default" %>
		  <%= f.submit 'Enviar', class: "btn btn-default" %>
		</div>
	</div>
<% end %>

app/views/clientes/edit.html.erb
<h2 class="page-header">Editar proveedor</h2>
<div class="row">
<%= render 'form' %>
</div>

app/views/clientes/index.html.erb
<h2 class="page-header">Clientes</h2>

<div class="dataTable_wrapper">
	<table id="dataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
		<thead>
		  <tr>
		    <th>Nombre</th>
		    <th>Teléfono</th>
		    <th>Dirección fiscal</th>
		    <th>RFC</th>
				<th>Responsable</th>
		    <th></th>
				
		  </tr>
		</thead>

		<tbody>
		  <% @clientes.each do |cliente| %>
		    <tr>
		      <td><%= cliente.nombre %></td>
		      <td><%= cliente.telefono %></td>
		      <td><%= cliente.direccion_fiscal %></td>
		      <td><%= cliente.rfc %></td>
				  <td><%= cliente.vendedor.nombre %></td>
		      <td><%= link_to "<span class=\"glyphicon glyphicon-info-sign\"></span>".html_safe, cliente %>
					<% if current_user.is_admin %>
		      	<%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_cliente_path(cliente) %>
		      	<%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, cliente, method: :delete, data: { confirm: '¿Estás seguro?' } %>
					<% end %>
					</td>
		    </tr>
		  <% end %>
		</tbody>
	</table>
</div>

<% if current_user.is_admin %>
	<%= link_to 'Nuevo Cliente', new_cliente_path, class: "btn btn-default" %>
<% end %>
<%= link_to 'Exportar CSV', clientes_path(format: :csv), class: "btn btn-default" %>

app/views/clientes/new.html.erb
<h2 class="page-header">Nuevo cliente</h2>

<%= render 'form' %>

app/views/clientes/show.html.erb
<div class="row">
	<p></p>
	<div class="col-lg-4">
		<div class="well well-lg">
		<h4>  <%= @cliente.nombre %></h4>
			<p>
			  <strong>Teléfono:</strong>
			  <%= @cliente.telefono %>
			</p>

			<p>
			  <strong>Dirección fiscal:</strong>
			  <%= @cliente.direccion_fiscal %>
			</p>

			<p>
			  <strong>RFC:</strong>
			  <%= @cliente.rfc %>
			</p>

			<%= link_to 'Ver tiendas', cliente_tiendas_clientes_path(@cliente), class: "btn btn-default" %>
			
		</div>
	</div>
</div>
<% if current_user.is_admin %>
<%= link_to 'Editar', edit_cliente_path(@cliente), class: "btn btn-default" %>
<% end %>
<%= link_to 'Regresar', clientes_path, class: "btn btn-default" %>