config/routes.rb
Rails.application.routes.draw do
	get ':controller(/:action)', controller: /[^\/]+/, action: /stats/

  resources :pedidos, except: [:edit, :update] do
		resources :pedidos_cantidades, except: [:index, :show]
	end

	get 'pedidos/:id/recibir', to: 'pedidos#recibir', as: 'recibir_pedido'
  get 'pedidos/:id/place', to: 'pedidos#place', as: 'place_pedido'

  resources :ordenes do
		resources :ordenes_cantidades, except: [:index, :show]
	end

  get 'ordenes/:id/place', to: 'ordenes#place', as: 'place_orden'
  get 'ordenes/:id/asignar_repartidor', to: 'ordenes#asignar_repartidor', as: 'asignar_repartidor'
	patch 'ordenes/:id/update_repartidor', to: 'ordenes#update_repartidor', as: 'update_repartidor'
  get 'ordenes/:id/entregar', to: 'ordenes#entregar', as: 'entregar_orden'

  resources :repartidores

  resources :clientes do
		resources :tiendas_clientes, shallow: true
  end

  resources :relojes

  resources :vendedores

  resources :proveedores

  devise_for :users, :skip => [:registrations]                                          
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
	end

	post 'ordenes/update_tiendas', as: 'update_tiendas'
	post 'ordenes_cantidades/update_relojes', as: 'update_relojes'
  get 'reparto', to: 'reparto#index', as: 'reparto'

  root 'home#inicio'

	get '*path' => redirect('/')

end

app/views/shared/_nav.html.erb
<!-- Navigation -->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">Watch Design International México</a>
</div>
<!-- /.navbar-header -->
<ul class="nav navbar-top-links navbar-right">
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">
<span class="glyphicon glyphicon-user"></span> <span class="glyphicon glyphicon-menu-down"></span>
</a>
<ul class="dropdown-menu dropdown-user">
<li><a href="#"><span class="glyphicon glyphicon-user"></span> <%= current_user.email %></a>
</li>
<li><a href="/users/edit" rel="nofollow" data-method="get"><span class="glyphicon glyphicon-cog"></span> Editar usuario</a>
</li>
<li class="divider"></li>
<li>
<li><a href="/users/sign_out" rel="nofollow" data-method="delete"><span class="glyphicon glyphicon-log-out"></span> Cerrar sesión</a>
</li>
</ul>
<!-- /.dropdown-user -->
</li>
<!-- /.dropdown -->
</ul>

app/views/shared/_sidebar.html.erb
<!-- Sidebar -->
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li>
                <a href="/"><span class="glyphicon glyphicon-dashboard"></span> Inicio</a>
            </li>
            <% if current_user.is_admin %>
            <li>
                <a data-toggle="collapse" data-target="#charts" aria-expanded="false" aria-controls="coll">
								<span class="glyphicon glyphicon-stats"></span> Estadísticas<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse" id="charts">
                    <li>
                        <a href="/ordenes/stats">Ventas</a>
                    </li>
                    <li>
                        <a href="/pedidos/stats">Compras</a>
                    </li>
										<li>
                        <a href="/relojes/stats">Relojes</a>
                    </li>
                </ul>
                <!-- /.nav-second-level -->
            </li>
						<% end %>
						<% unless current_user.repartidor %>
            <li>
								<a data-toggle="collapse" data-target="#tablas" aria-expanded="false" aria-controls="coll">
                <span class="glyphicon glyphicon-list-alt"></span> Tablas<span class="fa arrow"></span></a>
								<ul class="nav nav-second-level collapse" id="tablas">
										<li>
                        <%= link_to 'Órdenes', ordenes_path %></td>
                    </li>
										<% if current_user.is_admin %>      
												<li>
				                    <%= link_to 'Pedidos', pedidos_path %></td>
				                </li>
										<% end %>
										<li>
                        <%= link_to 'Relojes', relojes_path %></td>
                    </li>										
										<li>
                        <%= link_to 'Clientes', clientes_path %></td>
                    </li>       
										<% if current_user.is_admin %>       
												<li>
				                    <%= link_to 'Proveedores', proveedores_path %></td>
				                </li>
												<li>
				                    <%= link_to 'Vendedores', vendedores_path %></td>
				                </li>
												<li>
				                    <%= link_to 'Repartidores', repartidores_path %></td>
				                </li>
                    <% end %>
                </ul>
            </li>
						<% else %>
            <li>
								<a href="/reparto"><span class="glyphicon glyphicon-plane"></span> Reparto</a>
            </li>
						<% end %>
        </ul>
    </div>
    <!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->