config/routes.rb
Rails.application.routes.draw do
	get ':controller(/:action)', controller: /[^\/]+/, action: /stats/

  resources :pedidos, except: [:edit, :update] do
		resources :pedidos_cantidades, except: [:index, :show]
	end

	get 'pedidos/:id/recibir', to: 'pedidos#recibir', as: 'recibir_pedido'
  get 'pedidos/:id/place', to: 'pedidos#place', as: 'place_pedido'

  resources :ordenes do
		resources :ordenes_cantidades, except: [:index, :show]
	end

  get 'ordenes/:id/place', to: 'ordenes#place', as: 'place_orden'
  get 'ordenes/:id/asignar_repartidor', to: 'ordenes#asignar_repartidor', as: 'asignar_repartidor'
	patch 'ordenes/:id/update_repartidor', to: 'ordenes#update_repartidor', as: 'update_repartidor'
  get 'ordenes/:id/entregar', to: 'ordenes#entregar', as: 'entregar_orden'

  resources :repartidores

  resources :clientes do
		resources :tiendas_clientes, shallow: true
  end

  resources :relojes

  resources :vendedores

  resources :proveedores

  devise_for :users, :skip => [:registrations]                                          
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
	end

	post 'ordenes/update_tiendas', as: 'update_tiendas'
	post 'ordenes_cantidades/update_relojes', as: 'update_relojes'
  get 'reparto', to: 'reparto#index', as: 'reparto'

  root 'home#inicio'

	get '*path' => redirect('/')

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
	belongs_to :proveedor, inverse_of: :pedidos
	has_many :pedidos_cantidades, dependent: :destroy
	has_many :relojes, through: :pedidos_cantidades

	validates :proveedor_id, presence: true

	def self.to_csv
		CSV.generate do |csv|
		  csv << ['id', 'proveedor', 'fecha_pedido', 'fecha_recibido', 'total']
		  all.each do |pedido|
				csv << [pedido.id, pedido.proveedor.nombre, pedido.fecha_pedido, pedido.fecha_entrega, pedido.total]
		  end
  	end
	end

	def self.suma_total
		self.sum("total")
	end

	def proveedor
		Proveedor.unscoped.where(id: proveedor_id).first
	end

	def recibido?
		!fecha_entrega.nil?
	end

	def total
		if fecha_pedido
			read_attribute(:total)
		else
			total = 0
			pedidos_cantidades.each do |pc|
				total += pc.subtotal
			end
			total
		end
	end

	def self.compras_dia
		select("total").group_by_day(:fecha_pedido, last: 30 ).sum("total")
	end

	def self.compras_mes
		select("total").group_by_month(:fecha_pedido, last: 12).sum("total")
	end

	def self.compras_proveedor
		data = {}
		final = {}
		PedidoCantidad.all.map do |pc|
			proveedor = pc.pedido.proveedor.id
			data.has_key?(proveedor) ? data[proveedor] += pc.subtotal : data[proveedor] = pc.subtotal
		end
		data.map do |d|
			final[Proveedor.find(d.first).nombre] = d.second
		end
		final
	end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :ensure_admin!
  before_action :set_pedido, only: [:show, :edit, :update, :destroy, :recibir, :place]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all

		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.csv { send_data @pedidos.to_csv }
			format.pdf do
				render pdf: 'pedidos',                  # file name
				layout: 'layouts/application.pdf.erb',  # layout used
				show_as_html: params[:debug].present?    # allow debuging
			end
    end
  end
  
  def stats
		@compras_dia = Pedido.compras_dia
		@compras_mes = Pedido.compras_mes
		@compras_proveedor = Pedido.compras_proveedor

		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.pdf do
				render pdf: 'pedidos',                 # file name
				javascript_delay: 2000,
				layout: 'layouts/application.pdf.erb',  # layout used
				show_as_html: params[:debug].present?    # allow debuging
			end
		end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
		@pedidos_cantidades = @pedido.pedidos_cantidades
		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.pdf do
				render pdf: 'pedido',                 # file name
				layout: 'layouts/application.pdf.erb',  # layout used
				show_as_html: params[:debug].present?    # allow debuging
			end
		end
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
		@proveedores = Proveedor.joins(:relojes).distinct.order('nombre asc')
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)
		@proveedores = Proveedor.joins(:relojes).distinct.order('nombre asc')

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'El pedido se creó exitosamente.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
		unless @pedido.fecha_pedido    
			@pedido.destroy
		  respond_to do |format|
		    format.html { redirect_to pedidos_url, notice: 'El pedido se borró exitosamente.' }
		    format.json { head :no_content }
		  end
		else		
			redirect_to :back, alert: 'No se puede borrar un pedido que ya ha sido enviado.'
    end
  end

	def place
		unless @pedido.pedidos_cantidades.empty?
			@pedido.update(total: @pedido.total)
			@pedido.update(fecha_pedido: Time.now)
			redirect_to @pedido, notice: 'El pedido fue completado exitosamente.'
		else
			redirect_to @pedido, alert: 'No hay productos en el pedido.'
		end
	end

  def recibir
		if @pedido.fecha_pedido
			@pedido.transaction do
				@pedido.update(fecha_entrega: Time.now)
				cantidades = @pedido.pedidos_cantidades
				@pedido.relojes.each do |reloj|
					reloj.stock += cantidades.where(reloj_id: reloj.id).first.cantidad
					reloj.save
				end
			end
			redirect_to :back, notice: 'El pedido fue recibido exitosamente.'
		else
			redirect_to pedidos_url, alert: 'El pedido no ha sido completado.'
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:fecha_entrega, :proveedor_id)
    end
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido) do |f| %>
  <% if @pedido.errors.any? %>
    <div id="error_explanation">
      <h4>Hay <%= pluralize(@pedido.errors.count, "error") %>:</h4>

      <ul>
      <% @pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="col-lg-6">
		<div class="form-group">
      <label>Proveedor</label><br>
      <%= f.collection_select(:proveedor_id, @proveedores, :id, :nombre, {prompt: "Selecciona"}, {class: "form-control"}) %>
    </div>
		<div class="actions">
		  <%= f.submit 'Enviar', class: "btn btn-default" %>
		</div>
	</div>
<% end %>

app/views/pedidos/index.html.erb
<h2 class="page-header">Pedidos</h2>
<div class="dataTable_wrapper">
	<table id="dataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
		<thead>
		  <tr>
			<th>Proveedor</th>
		    <th>Fecha pedido</th>
		    <th>Fecha recibido</th>
			<th>Total</th>
		    <th></th>
		  </tr>
		</thead>

		<tbody>
		  <% @pedidos.each do |pedido| %>
		    <tr>
					<td><%= pedido.proveedor.nombre %></td>
		      <td><%= pedido.fecha_pedido.strftime("%d-%m-%Y %H:%M") if pedido.fecha_pedido %></td>
		      <td>
						<% if pedido.recibido? %>	
							<%= pedido.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
						<% elsif pedido.fecha_pedido %>
							<%= link_to 'Recibir', recibir_pedido_path(pedido), class: "btn btn-success btn-sm" %>
						<% end %>
			  </td>
			  <td><%= number_to_currency(pedido.total) %></td>	
					<td>
						<%= link_to "<span class=\"glyphicon glyphicon-info-sign\"></span>".html_safe, pedido %>
						<% unless pedido.fecha_pedido %>
							<%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, pedido, method: :delete, data: { confirm: '¿Estás seguro?' } %>
						<% end %>
					</td>
		    </tr>
		  <% end %>
		</tbody>
	</table>
</div>
<br>

<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to 'Nuevo pedido', new_pedido_path, class: "btn btn-default" %></li>
  <li role="presentation" class="dropdown">
    <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
      Exportar
      <span class="caret"></span>
    </a>
    <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
      <li role="presentation"><%= link_to 'PDF', pedidos_path(format: :pdf) %></li>
      <li role="presentation"><%= link_to 'CSV', pedidos_path(format: :csv) %></li>
    </ul>
  </li>
</ul>

app/views/pedidos/index.pdf.erb
<h2 class="page-header">Pedidos</h2>
<div class="dataTable_wrapper">
	<table id="dataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
  		<thead>
			<tr>
			 <th>Proveedor</th>
		    <th>Fecha pedido</th>
		    <th>Fecha recibido</th>
			<th>Total</th>	
			</tr>
  		</thead>

  		<tbody>
    		<% @pedidos.each do |pedido| %>
      	<tr>
					<td><%= pedido.proveedor.nombre %></td>
		      		<td><%= pedido.fecha_pedido.strftime("%d-%m-%Y %H:%M") if pedido.fecha_pedido %></td>
		      		<td>
						<% if pedido.recibido? %>	
							<%= pedido.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
						<% end %>
					</td>
					<td><%= number_to_currency(pedido.total) %></td>
      	</tr>
			<% end %>
		</tbody>
	</table>
</div>
<p></p>
<div align = "right">
	<strong>Compras totales:</strong>
	<%= number_to_currency(Pedido.sum("total")) %>
</div>

app/views/pedidos/new.html.erb
<h2 class="page-header">Nuevo pedido</h2>

<%= render 'form' %>

app/views/pedidos/show.html.erb
<div class="row">
	<p></p>
	<div class="col-lg-4">
		<div class="well well-lg">
			<h4><%= @pedido.proveedor.nombre %></h4>
		
			<% if @pedido.fecha_pedido %>			
				<p>
					<strong>Fecha pedido:</strong>
					<%= @pedido.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
				</p>
			<% end %>
		
			<% if @pedido.recibido? %>
				<p>
					<strong>Fecha recibido:</strong>
					<%= @pedido.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
				</p>
			<% end %>

			<p>
				<strong>Total:</strong>
				<div id="total"><%= number_to_currency(@pedido.total) %></div>
			</p>
		</div>
			
		<%= link_to 'Regresar', pedidos_path, class: "btn btn-default" %>
		<% if @pedido.fecha_pedido %>
			<%= link_to 'Exportar a PDF', pedido_path(@pedido, format: 'pdf'), class: "btn btn-default" %>
		<% end %>
	</div>
		

	<div class="col-lg-8">
		<%= render "pedidos_cantidades/index" %>

		<% unless @pedido.fecha_pedido %>
			<div class="col-md-offset-6">			
				<%= link_to new_pedido_pedido_cantidad_path(@pedido), remote: true do %>		
					<button class="btn btn-default">Agregar producto</button>
				<% end %>
				<%= link_to 'Completar pedido', place_pedido_path(@pedido), class: "btn btn-default" %>
			</div>
		<% end %>

	</div>
</div>

<div class="row">
  <div class="col-lg-6">
		<div id="cantidad-form" style="display:none;"></div>
	</div>
</div>

app/views/pedidos/show.pdf.erb
<div class="row">
	<p></p>
	<div class="col-lg-4">
		<div class="well well-lg">
			<h4><%= @pedido.proveedor.nombre %></h4>
		
			<% if @pedido.fecha_pedido %>			
				<p>
					<strong>Fecha pedido:</strong>
					<%= @pedido.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
				</p>
			<% end %>
		
			<% if @pedido.recibido? %>
				<p>
					<strong>Fecha recibido:</strong>
					<%= @pedido.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
				</p>
			<% end %>

			<p>
				<strong>Total:</strong>
				<div id="total"><%= number_to_currency(@pedido.total) %></div>
			</p>
		</div>
	</div>
</div>

<div class="row">
	<h3>Productos</h3>
	<table class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
		<thead>
			<tr>
				<th>Línea</th>
				<th>Modelo</th>
				<th>Cantidad</th>
				<th>Subtotal</th>
			</tr>
		</thead>
		<tbody id="cantidades">
			<% @pedidos_cantidades.each do |pedido_cantidad| %>
				<tr>
					<td><%= pedido_cantidad.reloj.marca %></td>
					<td><%= pedido_cantidad.reloj.modelo %></td>
					<td><%= pedido_cantidad.cantidad %></td>
					<td><%= number_to_currency(pedido_cantidad.subtotal) %></td>
				</tr>
			<% end %>
		</tbody>
	<table>
</div>

app/views/pedidos/stats.html.erb
<h2 class="page-header">Estadísticas de compras</h2>
<a href="/pedidos/stats.pdf" data-method="get" class='btn btn-default'>Exportar a PDF</a>
<div class = row>
	<p></p>
	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras diarias en los últimos 30 días 
			</div>                       
			<div class="panel-body">
			<%= area_chart(@compras_dia) %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras mensuales en el último año
			</div>                       
			<div class="panel-body">
			<%= area_chart(@compras_mes) %>
			</div>
		</div>
	</div>
	
	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras por proveedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart(@compras_proveedor) %>
			</div>
		</div>
	</div>
</div>

app/views/pedidos/stats.pdf.erb
<h2 class="page-header">Estadísticas de compras</h2>

<div class = row>
	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras diarias en los últimos 30 días 
			</div>                       
			<div class="panel-body">
			<%= area_chart(@compras_dia) %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras mensuales en el último año
			</div>                       
			<div class="panel-body">
			<%= area_chart(@compras_mes) %>
			</div>
		</div>
	</div>
	
	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Compras por proveedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart(@compras_proveedor) %>
			</div>
		</div>
	</div>
</div>