config/routes.rb
Rails.application.routes.draw do
	get ':controller(/:action)', controller: /[^\/]+/, action: /stats/

  resources :pedidos, except: [:edit, :update] do
		resources :pedidos_cantidades, except: [:index, :show]
	end

	get 'pedidos/:id/recibir', to: 'pedidos#recibir', as: 'recibir_pedido'
  get 'pedidos/:id/place', to: 'pedidos#place', as: 'place_pedido'

  resources :ordenes do
		resources :ordenes_cantidades, except: [:index, :show]
	end

  get 'ordenes/:id/place', to: 'ordenes#place', as: 'place_orden'
  get 'ordenes/:id/asignar_repartidor', to: 'ordenes#asignar_repartidor', as: 'asignar_repartidor'
	patch 'ordenes/:id/update_repartidor', to: 'ordenes#update_repartidor', as: 'update_repartidor'
  get 'ordenes/:id/entregar', to: 'ordenes#entregar', as: 'entregar_orden'

  resources :repartidores

  resources :clientes do
		resources :tiendas_clientes, shallow: true
  end

  resources :relojes

  resources :vendedores

  resources :proveedores

  devise_for :users, :skip => [:registrations]                                          
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
		patch 'users/:id' => 'devise/registrations#update', :as => 'user_registration'            
	end

	post 'ordenes/update_tiendas', as: 'update_tiendas'
	post 'ordenes_cantidades/update_relojes', as: 'update_relojes'
  get 'reparto', to: 'reparto#index', as: 'reparto'

  root 'home#inicio'

	get '*path' => redirect('/')

end

app/controllers/ordenes_controller.rb
class OrdenesController < ApplicationController
  before_action :ensure_vendedor!, except: [:entregar, :asignar_repartidor, :update_repartidor]
  before_action :ensure_admin!, only: [:asignar_repartidor, :update_repartidor]
  before_action :ensure_repartidor!, only: :entregar
  before_action :validar_permisos, only: [:show, :edit, :update, :destroy, :place]
	before_action :ensure_not_placed, only: [:edit, :update, :destroy]
  before_action :set_vendedor, only: [:index, :new, :create, :edit]
  before_action :set_orden, only: [:asignar_repartidor, :update_repartidor, :entregar]

  # GET /ordenes
  # GET /ordenes.json
  def index
    @ordenes = @vendedor ? Orden.por_vendedor(@vendedor.id) : Orden.all

		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.csv { send_data @ordenes.to_csv }
			format.pdf do
				render pdf: 'ordenes',                  # file name
				layout: 'layouts/application.pdf.erb',  # layout used
				show_as_html: params[:debug].present?    # allow debuging
			end
		end
  end

  def stats
		@ventas_dia = Orden.ventas_dia
		@ventas_mes = Orden.ventas_mes
		@ventas_proveedor = Orden.ventas_proveedor
		@ventas_vendedor = Orden.ventas_vendedor
		@ventas_cliente = Orden.ventas_cliente

		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.pdf do
				render pdf: 'ordenes',                 # file name
				javascript_delay: 2000,
				layout: 'layouts/application.pdf.erb',  # layout used
				show_as_html: params[:debug].present?    # allow debuging
			end
    end
  end

  # GET /ordenes/1
  # GET /ordenes/1.json
  def show
		@ordenes_cantidades = @orden.ordenes_cantidades
		respond_to do |format|
			format.html { render layout: "dataTables" }
			format.pdf { render pdf: 'orden', layout: 'layouts/application.pdf.erb' }
		end
  end

  # GET /ordenes/new
  def new
    @orden = Orden.new
		set_options_for_selects(@vendedor)
  end

  # GET /ordenes/1/edit
  def edit
		set_options_for_selects(@vendedor)
  end

  # POST /ordenes
  # POST /ordenes.json
  def create
    @orden = Orden.new(orden_params)
		set_options_for_selects(@vendedor)

    respond_to do |format|
      if current_user.tiene_permiso_sobre?(@orden) && @orden.save
        format.html { redirect_to @orden, notice: 'La orden se creó exitosamente.' }
        format.json { render :show, status: :created, location: @orden }
      else
        format.html { render :new }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordenes/1
  # PATCH/PUT /ordenes/1.json
  def update
    respond_to do |format|
      if @orden.update(orden_params)
        format.html { redirect_to @orden, notice: 'La orden se actualizó exitosamente.' }
        format.json { render :show, status: :ok, location: @orden }
      else
        format.html { render :edit }
        format.json { render json: @orden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenes/1
  # DELETE /ordenes/1.json
  def destroy
		@orden.destroy
	  respond_to do |format|
	    format.html { redirect_to ordenes_url, notice: 'La orden se borró exitosamente.' }
	    format.json { head :no_content }
	  end
  end

	def update_tiendas
		cliente = Cliente.find(params[:cliente_id])
		@tiendas_clientes = cliente.tiendas_clientes.map{|t| [t.nombre, t.id]}
	end

  def place
		unless @orden.ordenes_cantidades.empty?
			@orden.update(total: @orden.total)
			@orden.update(fecha_pedido: Time.now)
			redirect_to @orden, notice: 'La orden fue completada exitosamente.'
		else
			redirect_to @orden, alert: 'No hay productos en la orden.'
		end
	end

	def asignar_repartidor
		if @orden.fecha_pedido && !@orden.entregada?
			@repartidores = Repartidor.all
		else
			redirect_to ordenes_url, alert: 'No puedes asignar esta orden a un repartidor.'
		end
  end

	def update_repartidor
		permitted = params.require(:orden).permit(:repartidor_id)
		if permitted[:repartidor_id].blank?
			redirect_to :asignar_repartidor, alert: 'El repartidor no puede estar vacío.'
		elsif @orden.fecha_pedido && !@orden.entregada?
      @orden.update(permitted)
			redirect_to @orden, notice: 'El repartidor se asignó exitosamente.'
		end
	end

	def entregar
		if !current_user.is_admin
			if @orden.repartidor != current_user.repartidor
				redirect_to reparto_path, alert: 'No puedes entregar una orden que no te hayan asignado.'
			else
				@orden.update(fecha_entrega: Time.now)
				redirect_to reparto_path, notice: 'La orden se marcó como entregada.'
			end
		elsif @orden.fecha_pedido && @orden.repartidor
			@orden.update(fecha_entrega: Time.now)
			redirect_to ordenes_url, notice: 'La orden se marcó como entregada.'
		else
			redirect_to ordenes_url, alert: 'La orden no ha sido completada.'
		end
	end

  private
		def set_options_for_selects(vendedor)
			if vendedor
				@clientes = Cliente.con_tiendas.where(vendedor_id: vendedor.id)
				@tiendas_clientes = TiendaCliente.por_vendedor(vendedor.id)
			else
				@clientes = Cliente.con_tiendas
				@tiendas_clientes = TiendaCliente.all
			end
		end

		def validar_permisos
			set_orden
			unless current_user.tiene_permiso_sobre? @orden
				redirect_to ordenes_url, alert: 'No tienes los permisos necesarios.'
			end
		end

		def ensure_not_placed
			set_orden
			if @orden.fecha_pedido
				redirect_to orden_url(@orden), alert: 'No se puede alterar una orden que ya ha sido completada.'
			end
		end

		# Use callbacks to share common setup or constraints between actions.
    def set_orden
      @orden = Orden.find(params[:id])
    end

    def set_vendedor
			@vendedor = current_user.vendedor
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orden_params
      params.require(:orden).permit(:fecha_entrega, :tienda_cliente_id, :repartidor_id)
    end
end

app/helpers/ordenes_helper.rb
module OrdenesHelper
end

app/views/ordenes/_form.html.erb
<%= form_for(@orden) do |f| %>
  <% if @orden.errors.any? %>
    <div id="error_explanation">
      <h4>Hay <%= pluralize(@orden.errors.count, "error") %>:</h4>

      <ul>
      <% @orden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="col-lg-6">
		<div class="form-group">
      <label>Cliente</label><br>
      <%= collection_select(nil, :cliente_id, @clientes, :id, :nombre, {prompt: "Selecciona"}, {class: "form-control", id: "cliente_select"}) %>
    </div>
		<div class="form-group">
      <label>Tienda</label><br>
      <%= f.collection_select(:tienda_cliente_id, @tiendas_clientes, :id, :nombre, {prompt: "Selecciona una tienda"}, {class: "form-control", id: "tienda_select"}) %>
    </div>
		<div class="actions">
	      <%= link_to 'Cancelar', ordenes_path,  class: "btn btn-default" %>		
		  <%= f.submit 'Enviar', class: "btn btn-default" %>  	
		</div>
	</div>
<% end %>

app/views/ordenes/asignar_repartidor.html.erb
<h2 class="page-header">Asignar repartidor</h2>

<div class="row">
	<%= form_for(@orden, url: update_repartidor_path) do |f| %>
		<div class="col-lg-6">
			<div class="form-group">
				<label>Repartidor</label><br>
				<%= f.collection_select(:repartidor_id, @repartidores, :id, :nombre, {prompt: "Selecciona"}, {class: "form-control", id: "repartidor_select"}) %>
			</div>
			<div class="actions">
				<%= f.submit 'Enviar', class: "btn btn-default" %>
				<%= link_to 'Cancelar', ordenes_path,  class: "btn btn-default" %> 	
			</div>
		</div>
	<% end %>
</div>

<div id="map-container">
  <div id="map-canvas"></div>
</div> <p></p>

<script>
	var markers = [];

	function initialize() {	
		var mapOptions = {
      center: new google.maps.LatLng(19.426958, -99.167869),
      zoom: 13,
      mapTypeId: google.maps.MapTypeId.NORMAL,
      panControl: true,
      scaleControl: false,
      streetViewControl: true,
      overviewMapControl: true
    };
    // initializing map
    map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);

		var geocoding  = new google.maps.Geocoder();
		var tienda = <%= @orden.tienda_cliente.to_json.html_safe %>;
		codeAddress(geocoding, tienda);

		$('#repartidor_select').change(function() {
			deleteMarkers();
      var id = $('#repartidor_select').val();
			var tiendas = <%= Orden.por_repartidor.to_json.html_safe %>;
		  for (var i = 0; i < tiendas.length; i++) {
				if (tiendas[i].id == id)
					codeAddress(geocoding, tiendas[i]);
			}
		});
	}

	function codeAddress(geocoding, tienda){
		var address = tienda.direccion;
		if(address.length > 0){
		  geocoding.geocode({'address': address},function(results, status){
		    if(status == google.maps.GeocoderStatus.OK){
		      map.setCenter(results[0].geometry.location);
		      var marker  =  new google.maps.Marker({
		        map: map,
		        position: results[0].geometry.location
		      });
					if (markers.length == 0)
					  marker.setIcon('http://maps.google.com/mapfiles/ms/icons/green-dot.png');	
					markers.push(marker);
		      }else{
		      alert("Geocode was not successful for the following reason: " + status);
		    }
		  });
		}else{
		  alert("Search field can't be blank");
		}
  }

	// Sets the map on all markers in the array.
	function setAllMap(map) {
		for (var i = 1; i < markers.length; i++) {
		  markers[i].setMap(map);
		}
  }

	// Deletes all markers in the array by removing references to them.
	function deleteMarkers() {
  	setAllMap(null);
 	  var actual = markers[0];
		markers = [];
		markers[0] = actual;
  }
</script>

app/views/ordenes/edit.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<h2 class="page-header">Editar orden</h1>

<%= render 'form' %>
<script>
  $(document).ready(function() {
    $('#cliente_select').change(function() {
      $.ajax({
        url: "<%= update_tiendas_path %>",
				type: "POST",
				beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: {
          cliente_id : $('#cliente_select').val()
        },
        dataType: "script"
      });
    });
  });
</script>

app/views/ordenes/index.html.erb
<h2 class="page-header">Órdenes</h2>

<div class="dataTable_wrapper">
	<table id="dataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
  		<thead>
			<tr>
			  <th>Cliente</th>
			  <th>Tienda</th>
			  <th>Fecha pedido</th>
			  <th>Fecha entrega</th>
			  <th>Total</th>		
			  <th></th>
			</tr>
  		</thead>

  		<tbody>
    		<% @ordenes.each do |orden| %>
      	<tr>
					<td><%= orden.tienda_cliente.cliente.nombre %></td>
					<td><%= orden.tienda_cliente.nombre %></td>
					<td>
						<% if orden.fecha_pedido %>
							<%= orden.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
						<% end %>
					</td>
					<td>
						<% if orden.entregada? %>
							<%= orden.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
						<% elsif orden.repartidor && current_user.is_admin %>
							<%= link_to 'Marcar entregada', entregar_orden_path(orden), class: "btn btn-success btn-sm" %>
						<% end %>
					</td>
					<td><%= number_to_currency(orden.total) %></td>
					<td><%= link_to "<span class=\"glyphicon glyphicon-info-sign\"></span>".html_safe, orden %>
					<% unless orden.fecha_pedido %>
						<%= link_to "<span class=\"glyphicon glyphicon-pencil\"></span>".html_safe, edit_orden_path(orden) %>
						<%= link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, orden, method: :delete, data: { confirm: '¿Estás seguro?' } %>
					<% end %>
					</td>
      	</tr>
			<% end %>
		</tbody>
	</table>
</div>

<ul class="nav nav-pills" role="tablist">
  <li role="presentation"><%= link_to 'Nueva orden', new_orden_path, class: "btn btn-default" %></li>
  <li role="presentation" class="dropdown">
    <a id="drop4" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
      Exportar
      <span class="caret"></span>
    </a>
    <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
      <li role="presentation"><%= link_to 'PDF', ordenes_path(format: :pdf) %></li>
      <li role="presentation"><%= link_to 'CSV', ordenes_path(format: :csv) %></li>
    </ul>
  </li>
</ul>

app/views/ordenes/index.pdf.erb
<h2 class="page-header">Órdenes</h2>
<div class="dataTable_wrapper">
	<table id="dataTable" class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
  		<thead>
			<tr>
			  <th>Cliente</th>
			  <th>Tienda</th>
			  <th>Fecha pedido</th>
			  <th>Fecha entrega</th>
			  <th>Total</th>		
			</tr>
  		</thead>

  		<tbody>
    		<% @ordenes.each do |orden| %>
      	<tr>
					<td><%= orden.tienda_cliente.cliente.nombre %></td>
					<td><%= orden.tienda_cliente.nombre %></td>
					<td>
						<% if orden.fecha_pedido %>
							<%= orden.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
						<% end %>
					</td>
					<td>
						<% if orden.entregada? %>
							<%= orden.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
						<% end %>
					</td>
					<td><%= number_to_currency(orden.total) %></td>
      	</tr>
			<% end %>
		</tbody>
	</table>
</div>
<p></p>
<div align = "right">
	<strong>Ventas totales:</strong>
	<%= number_to_currency(Orden.sum("total")) %>
</div>

app/views/ordenes/new.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<h2 class="page-header">Nueva orden</h2>

<%= render 'form' %>

<script>
  $(document).ready(function() {
    $('#cliente_select').change(function() {
      $.ajax({
        url: "<%= update_tiendas_path %>",
				type: "POST",
				beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        data: {
          cliente_id : $('#cliente_select').val()
        },
        dataType: "script"
      });
    });
  });
</script>

app/views/ordenes/show.html.erb
<div class="row">
	<p></p>
	<div class="col-lg-4">
		<div class="well well-lg">
		<h4><%= @orden.tienda_cliente.cliente.nombre %></h4>
		
			<p>
				<strong>Tienda:</strong>
				<%= @orden.tienda_cliente.nombre %>
			</p>

			<% if @orden.tiene_repartidor? %>
				<p>
					<strong>Repartidor:</strong>
					<%= @orden.repartidor.nombre %>
				</p>
			<% end %>

			<% if @orden.fecha_pedido %>
			<p>
				<strong>Fecha pedido:</strong>
				<%= @orden.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
			</p>
			<% end %>

			<% if @orden.entregada? %>
			<p>
				<strong>Fecha entrega:</strong>
				<%= @orden.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
			</p>
			<% end %>

			<p>
				<strong>Total:</strong>
				<div id="total"><%= number_to_currency(@orden.total) %></div>
			</p>
		</div>

		<% if !@orden.fecha_pedido %>
			<%= link_to 'Editar', edit_orden_path(@orden),  class: "btn btn-default" %>
		<% elsif !@orden.entregada? %>
			<%= link_to 'Repartidor', asignar_repartidor_path(@orden),  class: "btn btn-default" %>
		<% end %>
		<%= link_to 'Regresar', ordenes_path,  class: "btn btn-default" %>
	</div>

	<div class="col-lg-8">
		<%= render "ordenes_cantidades/index" %>

		<% unless @orden.fecha_pedido %>
		<div class="col-md-offset-6">
			<%= link_to new_orden_orden_cantidad_path(@orden), remote: true do %>
					<button class="btn btn-default">Agregar producto</button>
			<% end %>
			<%= link_to 'Completar orden', place_orden_path(@orden), class: "btn btn-default" %>
		</div>
		<% else %>
			<%= link_to 'Exportar a PDF', orden_path(@orden, format: 'pdf'), class: "btn btn-default" %>
		<% end %>

	</div>
</div>

<div class="row">
  <div class="col-lg-6">
		<div id="cantidad-form" style="display:none;"></div>
	</div>
</div>

app/views/ordenes/show.pdf.erb
<div class="row">
	<p></p>
	<div class="col-lg-4">
		<div class="well well-lg">
		<h4><%= @orden.tienda_cliente.cliente.nombre %></h4>
		
			<p>
				<strong>Tienda:</strong>
				<%= @orden.tienda_cliente.nombre %>
			</p>

			<% if @orden.tiene_repartidor? %>
				<p>
					<strong>Repartidor:</strong>
					<%= @orden.repartidor.nombre %>
				</p>
			<% end %>

			<% if @orden.fecha_pedido %>
			<p>
				<strong>Fecha pedido:</strong>
				<%= @orden.fecha_pedido.strftime("%d-%m-%Y %H:%M") %>
			</p>
			<% end %>

			<% if @orden.entregada? %>
			<p>
				<strong>Fecha entrega:</strong>
				<%= @orden.fecha_entrega.strftime("%d-%m-%Y %H:%M") %>
			</p>
			<% end %>

			<p>
				<strong>Total:</strong>
				<div id="total"><%= number_to_currency(@orden.total) %></div>
			</p>
		</div>
	</div>
</div>

<div class="row">
	<h3>Productos</h3>
	<div class="dataTable_wrapper">
		<table class="table table-striped table-bordered table-hover" width="100%" cellspacing="0">
			<thead>
				<tr>
					<th>Proveedor</th>
					<th>Modelo</th>
					<th>Cantidad</th>
					<th>Subtotal</th>
				</tr>
			</thead>
			<tbody id="cantidades">
				<% @ordenes_cantidades.each do |orden_cantidad| %>
					<tr>
						<td><%= orden_cantidad.reloj.proveedor.nombre %></td>
						<td><%= orden_cantidad.reloj.modelo %></td>
						<td><%= orden_cantidad.cantidad %></td>
						<td><%= number_to_currency(orden_cantidad.subtotal) %></td>
					</tr>
				<% end %>
			</tbody>
		<table>
	</div>
</div>

app/views/ordenes/stats.html.erb
<h2 class="page-header">Estadísticas de ventas</h2>
<a href="/ordenes/stats.pdf" data-method="get" class='btn btn-default'>Exportar a PDF </a>
<div class = row>
	<p></p>
	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas diarias en los últimos 30 días 
			</div>                       
			<div class="panel-body">
			<%= area_chart @ventas_dia %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas mensuales en el último año 
			</div>                       
			<div class="panel-body">
			<%= area_chart @ventas_mes %>
			</div>
		</div>
	</div>

	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por proveedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart @ventas_proveedor %>
			</div>
		</div>
	</div>

	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por vendedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart @ventas_vendedor %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por cliente 
			</div>                       
			<div class="panel-body">
			<%= pie_chart @ventas_cliente %>
			</div>
		</div>
	</div>
</div>

app/views/ordenes/stats.pdf.erb
<h2 class="page-header">Estadísticas de ventas</h2>

<div class = row>
	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas diarias en los últimos 30 días 
			</div>                       
			<div class="panel-body">
			<%= area_chart @ventas_dia %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas mensuales en el último año 
			</div>                       
			<div class="panel-body">
			<%= area_chart @ventas_mes %>
			</div>
		</div>
	</div>

	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por proveedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart @ventas_proveedor %>
			</div>
		</div>
	</div>

	<div class="col-lg-6"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por vendedor 
			</div>                       
			<div class="panel-body">
			<%= column_chart @ventas_vendedor %>
			</div>
		</div>
	</div>

	<div class="col-lg-12"> 
		<div class="panel panel-default">
			<div class="panel-heading">
				Ventas por cliente 
			</div>                       
			<div class="panel-body">
			<%= pie_chart @ventas_cliente %>
			</div>
		</div>
	</div>
</div>

app/views/ordenes/update_tiendas.js.erb
$('#tienda_select').html("<%= escape_javascript(options_for_select(@tiendas_clientes)) %>");